
setup.sexPhases = ["tease", "penetration", "climax", "continue","end"];


setup.sexpositions = {
    // label: player-readable label
    // frequency: how often an NPC chooses this position
    // Bottom: whoever has one of these body parts can occupy the 'Bottom' position
    // Top: whoever has one of these body parts can occupy the 'Top' position (it's a little arbitrary but hey it's just a game)
    // cum locations: where it is possible to cum in this position (external bits only... any part penetrated by cumming part will additionally be available)
    // equal: Top/Bottom doesn't really matter
    // primary: this is a primary position (can be selected in one-on-one encounters, or is a position with the primary partner)
    // secondary positions: positions valid for additional partners
    "Standing":
    {
        label: "standing",
        "Bottom": ["Penis", "Vagina"],
        "Top": ["Penis", "Vagina"],
        "Bottom cum locations": ["on crotch", "on stomach", "on thigh"],
        "Top cum locations": ["on crotch", "on stomach", "on thigh"],
        "equal": true,
        primary: true,
        "secondary positions": ["Standing", "Standing From Behind"],
        furniture: ["small standing room", "large standing room"],
    },
    "Against Wall":
    {
        label: "against the wall",
        "Bottom": ["Penis", "Vagina"],
        "Top": ["Penis", "Vagina"],
        "Bottom cum locations": ["on crotch", "on stomach", "on thigh"],
        "Top cum locations": ["on crotch", "on stomach", "on thigh"],
        "equal": true,
        primary: true,
        "secondary positions": ["Standing"],
        furniture: ["vertical surface"],
    },
    "Against Wall From Behind":
    {
        label: "against the wall from behind",
        "Bottom": ["Penis", "Vagina","Ass","Asshole"],
        "Top": ["Penis","Vagina"],
        "Bottom cum locations": ["on wall"],
        "Top cum locations": ["on crotch", "on ass", "on thigh"],
        "label Top": "behind",
        "label Bottom": "against wall",
        primary: true,
        "secondary positions": ["Standing"],
        furniture: ["vertical surface"],
    },
    "Sitting":
    {
        label: "sitting",
        "Bottom": ["Ass","Leg"],
        "Top": ["Ass","Leg"],
        "Bottom cum locations": ["on crotch", "on stomach", "on thigh"],
        "Top cum locations": ["on crotch", "on stomach", "on thigh"],
        "label Top": "seated",
        "label Bottom": "seated",
        primary: true,
        "secondary positions": ["Standing", "Sit On Face"],
        furniture: ["large seat"],
    },
    "Lap ride":
    {
        label: "sitting",
        "Bottom": ["Ass","Leg"],
        "Top": ["Ass","Leg"],
        "Bottom cum locations": ["on crotch", "on stomach", "on thigh"],
        "Top cum locations": ["on crotch", "on stomach", "on thigh"],
        "label Top": "seated",
        "label Bottom": "seated",
        primary: true,
        "secondary positions": ["Standing", "Sit On Face"],
        furniture: ["small seat","large seat"],
    },
    "Reverse Lap ride":
    {
        label: "sitting",
        "Bottom": ["Ass","Leg"],
        "Top": ["Ass","Leg"],
        "Bottom cum locations": ["in the air"],
        "Top cum locations": ["on butt", "on back"],
        "label Top": "seated",
        "label Bottom": "seated",
        primary: true,
        "secondary positions": ["Standing", "Sit On Face"],
        furniture: ["small seat","large seat"],
    },
    "Perched Oral Service":
    {
        label: "perched oral service",
        "Bottom": ["Mouth"],
        "Top": ["Penis", "Vagina"],
        "Bottom cum locations": ["on face", "on chest", "on breasts"],
        "Top cum locations": ["in the air"],
        "label Bottom": "kneeling",
        "label Top": "seated",
        primary: true,
        "secondary positions": ["Standing", "Sit On Face"],
        furniture: ["small seat", "large seat"],
    },
    "Underneath Oral Service":
    {
        label: "underneath oral service",
        "Bottom": ["Mouth"],
        "Top": ["Penis", "Vagina"],
        "Bottom cum locations": ["on face", "on chest", "on breasts"],
        "Top cum locations": ["???"],
        "label Bottom": "kneeling underneath",
        "label Top": "seated",
        primary: true,
        "secondary positions": ["Doggy"],
        furniture: ["underspace"],
        furnitureOverridePreposition: "under",
    },
    "Standing From Behind":
    {
        label: "standing spoon",
        "Bottom": [],
        "Top": [],
        "Bottom cum locations": ["in the air"],
        "Top cum locations": ["on crotch", "on ass", "on thigh"],
        "label Top": "behind",
        "label Bottom": "in front",
        primary: true,
        "secondary positions": ["Standing"],
        furniture: ["small standing room", "large standing room"],
    },
    
    "Missionary":
    {
        label: "missionary",
        "Top": [],
        "Bottom": [],
        "Top cum locations": ["on crotch", "on stomach", "on thigh"],
        "Bottom cum locations": ["on crotch"],
        "label Top": "on Top",
        "label Bottom": "underneath",
        primary: true,
        "secondary positions": ["Sit On Face", "Kneeling By Face"],
        furniture: ["horizontal surface"],
        "Bottom dialogue tags": ["missionary Bottom"],
    },
    "Mating Press":
    {
        label: "missionary",
        "Top": [],
        "Bottom": [],
        "Top cum locations": ["on crotch", "on stomach", "on thigh"],
        "Bottom cum locations": ["on crotch"],
        "label Top": "on Top",
        "label Bottom": "underneath",
        primary: true,
        "secondary positions": ["Sit On Face", "Kneeling By Face"],
        furniture: ["horizontal surface"],
    },
    "From Behind":
    {
        label: "doggy",
        "Top": [],
        "Bottom": [],
        "Top cum locations": ["on crotch", "on ass", "on back"],
        "Bottom cum locations": ["on ground"],
        "label Top": "behind",
        "label Bottom": "on all fours",
        primary: true,
        "secondary positions": ["Squatting Before"],
        furniture: ["horizontal surface"],
        deprecated: true,
        "Top dialogue tags": ["from behind Top"],
        "Bottom dialogue tags": ["from behind Bottom"],
    },
    "Doggy":
    {
        label: "doggy",
        "Top": [],
        "Bottom": ["Vagina", "Asshole"],
        "Top cum locations": ["on crotch", "on ass", "on back"],
        "Bottom cum locations": ["on ground"],
        "label Top": "behind",
        "label Bottom": "on all fours",
        primary: true,
        "secondary positions": ["Squatting Before"],
        furniture: ["horizontal surface"],
        "Top dialogue tags": ["from behind Top"],
        "Bottom dialogue tags": ["from behind Bottom"],
    },
    "Bent Over":
    {
        label: "bent over",
        "Top": [],
        "Bottom": ["Vagina", "Asshole"],
        "Top cum locations": ["on crotch", "on ass", "on back"],
        "Bottom cum locations": ["on the ground"],
        "label Top": "behind",
        "label Bottom": "bent over",
        primary: true,
        "secondary positions": ["Standing", "Standing Before"],
        furniture: ["small seat","large seat"],
        furniturePrepositionIncluded: true,
        "Top dialogue tags": ["from behind Top"],
        "Bottom dialogue tags": ["from behind Bottom"],
    },
    "Prone Bone":
    {
        label: "prone bone",
        "Top": [],
        "Bottom": [],
        "Top cum locations": ["on crotch", "on ass", "on back"],
        "Bottom cum locations": ["on the ground"],
        "label Top": "on Top",
        "label Bottom": "beneath",
        primary: true,
        "secondary positions": ["Squatting Before"],
        furniture: ["horizontal surface"],
    },
    "Spooning":
    {
        label: "spooning",
        "Top": [],
        "Bottom": [],
        "Top cum locations": ["on crotch", "on ass", "back"],
        "Bottom cum locations": ["on the ground"],
        "label Top": "big spoon",
        "label Bottom": "little spoon",
        primary: true,
        "secondary positions": ["Kneeling By Face", "Sit On Face"],
        furniture: ["horizontal surface"],
    },
    "Double Decker":
    {
        label: "double decker",
        "Top": [],
        "Bottom": ["Vagina", "Ass"],
        "Top cum locations": ["on crotch", "on ass", "on thigh", "on back"],
        "Bottom cum locations": ["on yourself"],
        "label Top": "underneath",
        "label Bottom": "on Top",
        primary: true, /*Was False */
        "secondary positions": ["Kneeling By Face", "Sit On Face", "Kneeling Between Thighs"],
        furniture: ["horizontal surface"],
    },
    "Kneeling Between Thighs":
    {
        label: "kneeling between thighs",
        "Top": ["Penis","Vagina"],
        "Bottom": ["Vagina", "Asshole"],
        "Top cum locations": ["on crotch", "on thigh", "on stomach"],
        "Bottom cum locations": ["on face"],
        "label Top": "kneeling",
        "label Bottom": "on back",
        primary: true, /*Was False */
        "secondary positions": ["Kneeling By Face", "Sit On Face", "Double Decker"],
        furniture: ["horizontal surface"],
    },
    "Cowgirl":
    {
        label: "cowgirl",
        "Top": [],
        "Bottom": ["Vagina", "Asshole"],
        "Bottom cum locations": ["on crotch"],
        "Top cum locations": ["on crotch", "on stomach"],
        "force Bottom cum location": true,
        "label Top": "on Top",
        "label Bottom": "on back",
        primary: true,
        "secondary positions": ["Squatting Before", "Sit On Face", "Kneeling By Face"],
        furniture: ["horizontal surface"],
    },
    "Reverse Cowgirl":
    {
        label: "cowgirl",
        "Top": [],
        "Bottom": ["Vagina","Asshole"],
        "Bottom cum locations": ["in the air"],
        "Top cum locations": ["on crotch", "on thigh"],
        "force Bottom cum location": true,
        "label Top": "on Top",
        "label Bottom": "on back",
        primary: true,
        "secondary positions": ["Squatting Before", "Sit On Face", "Kneeling By Face"],
        furniture: ["horizontal surface"],
    },
    "Scissor":
    {
        label: "scissor",
        "Top": ["Penis","Vagina"],
        "Bottom": ["Penis","Vagina"],
        "Bottom cum locations": ["on crotch"],
        "Top cum locations": ["on crotch", "on stomach"],
        "force Bottom cum location": true,
        "label Top": "on Top",
        "label Bottom": "on back",
        primary: true,
        "secondary positions": ["Squatting Before", "Sit On Face", "Kneeling By Face"],
        furniture: ["horizontal surface"],
    },
    "Sit On Face":
    {
        label: "face-riding",
        "Top": ["Mouth","Tongue"], /*Originally Vagina, Penis*/
        "Bottom": ["Vagina","Penis","Asshole","Ass"],    /*Originally Vagina, Penis*/
        "Bottom cum locations": ["on yourself"],
        "Top cum locations": ["on face"],
        "label Top": "riding",
        "label Bottom": "on back",
        primary: true,
        "secondary positions": ["Squatting Before"],
        furniture: ["horizontal surface"],
    },
    "Kneeling":
    {
        label: "kneeling",
        "Bottom": ["Mouth"],
        "Top": ["Penis", "Vagina"],
        "Bottom cum locations": ["on the ground"],
        "Top cum locations": ["on face", "on chest", "on breasts"],
        "label Top": "receiving",
        "label Bottom": "giving",
        primary: true,
        "secondary positions": ["Kneeling"],
        furniture: ["small standing room", "large standing room"],
    },
    "Squatting Before": /* Check if needed*/
    {
        label: "squatting",
        "Bottom": ["Mouth"],
        "Top": ["Penis", "Vagina"],
        "Bottom cum locations": ["on the ground"],
        "Top cum locations": ["on face", "on chest", "on breasts"],
        "label Top": "receiving",
        "label Bottom": "giving",
        primary: false,
        "secondary positions": ["Kneeling"],
        furniture: ["small seat", "large seat"],
    },
    "Kneeling Over":
    {
        label: "kneeling over",
        "Bottom": ["Mouth"],
        "Top": ["Penis", "Vagina"],
        "Bottom cum locations": ["on the ground"],
        "Top cum locations": ["on face", "on chest", "on breasts"],
        "label Top": "receiving",
        "label Bottom": "giving",
        primary: true,
        "secondary positions": ["Kneeling", "Kneeling Over"],
        furniture: ["horizontal surface"],
    },
    "Kneeling By Face": /* Based on Height? */
    {
        label: "kneeling by face",
        "Bottom": ["Mouth"],
        "Top": ["Penis"],
        "Bottom cum locations": ["on yourself"],
        "Top cum locations": ["on face", "on chest", "on breasts"],
        "label Top": "receiving",
        "label Bottom": "giving",
        primary: false,
        furniture: ["horizontal surface"],
    },
    "Sixty-Nine":
    {
        label: "sixty-nine",
        "Top": ["Penis", "Vagina"],
        "Bottom": ["Vagina", "Penis"],
        "Top cum locations": ["on face", "on chest", "on breasts"],
        "Bottom cum locations": ["on face", "on chest", "on breasts"],
        primary: true,
        equal: true,
        furniture: ["horizontal surface"],
    },
    "Straddling Chest":
    {
        label: "straddling",
        "Top": ["Penis", "Vagina"],
        "Bottom": ["Chest","Breasts"],
        "Top cum locations": ["on face", "on chest", "on breasts"],
        "Bottom cum locations": ["on back"],
        "label Top": "on Top",
        "label Bottom": "underneath",
        primary: true,
        "secondary positions": ["Kneeling By Face"],
        furniture: ["horizontal surface"],
    },
    "Oral Service":
    {
        label: "oral service",
        "Bottom": ["Mouth"],
        "Top": ["Penis", "Vagina"],
        "Bottom cum locations": ["on yourself"],
        "Top cum locations": ["on face", "on chest", "on breasts"],
        "label Bottom": "giving",
        "label Top": "receiving",
        primary: true,
        "secondary positions": ["Kneeling By Face"],
        furniture: ["horizontal surface"],
    },
    "Laid Across On Back": /*Check */
    {
        label: "laid across",
        "Top": ["Penis"],
        "Bottom": ["Vagina", "Asshole"],
        "Top cum locations": ["on crotch", "on stomach", "on thigh"],
        "Bottom cum locations": ["on crotch"],
        "label Top": "between thighs",
        "label Bottom": "prone",
        primary: true,
        "secondary positions": ["Laid Across Oral Service"],
        furniture: ["bench", "horizontal surface"],
    },
    "Laid Across On Stomach": /*Check */
    {
        label: "laid across",
        "Top": ["Penis"],
        "Bottom": ["Vagina", "Asshole"],
        "Top cum locations": ["on crotch", "on stomach", "on thigh"],
        "Bottom cum locations": ["on crotch"],
        "label Top": "behind",
        "label Bottom": "prone",
        primary: true,
        "secondary positions": ["Laid Across Oral Service"],
        furniture: ["bench", "horizontal surface"],
    },
    "Laid Across Oral Service":
    {
        label: "laid across oral service",
        "Top": ["Penis"],
        "Bottom": ["Mouth"],
        "Top cum locations": ["on crotch", "on stomach", "on thigh"],
        "Bottom cum locations": ["on crotch"],
        "label Top": "receiving",
        "label Bottom": "giving",
        primary: true,
        "secondary positions": ["Laid Across On Back", "Laid Across On Stomach"],
        furniture: ["bench"],
    },

};



// positions: array of positions this act is possible for the average person in
// action type: array of "tease" or "penetrate" or "continue" or "end" for circumstances under which this act can be selected
//(tease engages parts, penetrate... penetrates and requires teasing first, continues require prior penetration, end ends engagement)
// Top parts: body parts that the person actively doing the thing needs
// Bottom parts: body parts that the person 'receiving' the thing needs
// masturbation: is this possible to do to oneself
// take virginity: array of parts this act takes virginity from
// Top arousal: increase arousal by this (orgasm at 1000, may be modified by other factors)
// Bottom arousal: increase arousal by this
// Top arousal cap: don't increase arousal if it's already over this number (prevent some otherwise arousing acts from leading to orgasm)
// Bottom arousal cap: don't increase arousal if it's already over this number
// remember as: make a sex memory ('given'/'received' is what it's recorded as for Top, Bottom is automatically reversed)
// act label substitution: used to replace Pussy and other non-inclusive nouns for bits

setup.sexacts = {
    "Kiss": /*You both kiss each other */
    {
        "positions": [ "Missionary", "Lap ride", "Laid Across On Back", "Laid Across On Stomach", "Mating Press", "Cowgirl", "Standing", "Sitting", "Against Wall","Spooning"],
        "action type": ["tease"],
        "Top parts": ["Mouth"],
        "Bottom parts": ["Mouth"],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 5,
        "Bottom arousal": 5,
        "Top arousal cap": 200,
        "Bottom arousal cap": 200,
        "remember as": ["kissed"],
        "Top dialogue tags": ["kissing"],
        "Bottom dialogue tags": ["kissing"],
    },
    "Pet Ears": /* Either you or they pet ears. */ 
    {
        "positions": [ "Standing","Lap ride", "Reverse Lap ride", "Sitting","Doggy", "Standing From Behind","Spooning"],
        /* Anthro ears? */
        "action type": ["tease"],
        
        "Top parts": ["Hand"],
        "Bottom parts": ["Ears"],

        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal":  40,
        "Top arousal cap": 400,
        "remember as": ["petting", "received"],
    },
    "Grope Breasts": /* Either you of the other grope's the other's breast */
    {
        "positions": [ "Missionary", "Sittng", "Lap ride", "Reverse Lap ride", "Laid Across On Back", "Mating Press", "Perched", "Doggy", "From Behind", "Cowgirl", "Reverse Cowgirl", "Kneeling Over", "Standing", "Standing From Behind", "Spooning", "Kneeling By Face", "Squatting Before", "Double Decker", "Kneeling Between Thighs", "Against Wall", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["tease"],

        "Top parts": ["Hand"],
        "Bottom parts": ["Breasts"],

        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 25,
        "Top arousal cap": 300,
        "Bottom arousal cap": 400,
        "Top dialogue tags": ["groping breasts"],
        "Bottom dialogue tags": ["breasts groped"],
    },
    "Tease Nipples":
    {
        "positions": [ "Missionary","Sitting", "Lap ride", "Laid Across On Back", "Mating Press", "Perched", "Prone Bone", "From Behind", "Cowgirl", "Reverse Cowgirl", "Kneeling Over", "Standing", "Standing From Behind", "Spooning", "Kneeling By Face", "Squatting Before", "Double Decker", "Kneeling Between Thighs", "Against Wall", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["tease"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Nipples"],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 30,
        "Top arousal cap": 400,
        "Bottom arousal cap": 600,
        "no Bottom arousal cap for": ["Sensitive Nipples"],
        "Top dialogue tags": ["groping breasts"],
        "Bottom dialogue tags": ["breasts groped"],
    },
        /* other stuff */
    "Fuck Tits": /* You use your cock on their tits */
    {
        "positions": ["Kneeling:Top", "Straddling Chest:Top"],
        "action type": ["tease"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Breasts"],
        "Top cum locations": ["on breasts"],
        "Bottom cum locations": [],
        "take virginity": [],
        "Top arousal": 40,
        "Bottom arousal":  10,
        "Bottom arousal cap": 400,
        "remember as": ["titfuck", "given"],
        "Top dialogue tags": ["fucking tits"],
        "Bottom dialogue tags": ["tits fucked"],
    },
    "Use Tits On Cock": /* You use your tits on their cock */
    {
        "positions": ["Kneeling:Top", "Straddling Chest:Top"],
        "action type": ["tease"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Breasts"],
        "Top cum locations": [],
        "Bottom cum locations": ["on breasts"],
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal":  40,
        "Top arousal cap": 400,
        "remember as": ["titfuck", "received"],
    },
    "Hotdog": /* You rub your cock on their ass */
    {
        "positions": [ "Standing From Behind:Top", "Reverse Lap ride:Top", "From Behind:Top", "Doggy:Top", "Bent Over:Top", "Spooning:Top", "Double Decker:Top", "Against Wall From Behind:Top"],
        "action type": ["tease"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Ass"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "take virginity": [],
        "Top arousal": 40,
        "Bottom arousal":  10,
        "Bottom arousal cap": 400,
        "remember as": ["hotdogging", "given"],
        "Top dialogue tags": ["hotdogging"],
        "Bottom dialogue tags": ["hotdogged"],
    },
    "Rub Ass On Cock": /* You rub your ass on their cock */
    {
        "positions": [ "Standing From Behind:Bottom", "Reverse Lap ride:Bottom", "From Behind:Bottom", "Doggy:Bottom", "Bent Over:Bottom", "Spooning:Bottom", "Double Decker:Bottom", "Against Wall From Behind:Bottom"],
        "action type": ["tease"],
        "Top parts": ["Ass"],
        "Bottom parts": ["Penis"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal":  40,
        "Top arousal cap": 400,
        "remember as": ["hotdogging", "received"],
    },
    "Press Face on Chest": 
    {
        "positions": [ "Missionary", "Lap ride", "Laid Across On Back", "Mating Press", "Sitting", "Cowgirl", "Kneeling Over", "Standing", "Against Wall","Face On Chest"],
        "action type": ["penetrate"],
        "Top parts": ["Head"],
        "Bottom parts": ["Chest","Breasts"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal":  0,
        "Top arousal cap": 0,
    },
    "Kiss Nipple":
    {
        "positions": [ "Missionary", "Laid Across On Back", "Mating Press", "Sitting", "Cowgirl", "Kneeling Over", "Standing", "Lap ride", "Against Wall","Face On Chest"],
        "action type": ["continue"],
        "Top parts": ["Head"],
        "Bottom parts": ["Chest"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 30,
        "Top arousal cap": 400,
        "Bottom arousal cap": 600,
        "no Bottom arousal cap for": ["Sensitive Nipples"],
    },
    "Lick Nipple":
    {
        "positions": [ "Missionary", "Laid Across On Back", "Mating Press", "Sitting", "Cowgirl", "Kneeling Over", "Standing", "Lap ride", "Against Wall","Face On Chest"],
        "action type": ["continue"],
        "Top parts": ["Head"],
        "Bottom parts": ["Chest"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 35,
        "Top arousal cap": 500,
        "Bottom arousal cap": 600,
        "no Bottom arousal cap for": ["Sensitive Nipples"],
    },
    "Suck Nipple":
    {
        "positions": [ "Missionary", "Lap ride", "Laid Across On Back", "Mating Press", "Sitting", "Cowgirl", "Kneeling Over", "Standing", "Lap ride", "Against Wall","Face On Chest"],
        "action type": ["continue"],
        "Top parts": ["Head"],
        "Bottom parts": ["Chest"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 40,
        "Top arousal cap": 600,
        "Bottom arousal cap": 800,
        "no Bottom arousal cap for": ["Sensitive Nipples"],
        "Top dialogue tags": ["sucking nipples"],
        "Bottom dialogue tags": ["nipples sucked"],
    },
    "Pull Face Back":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Head"],
        "Bottom parts": ["Chest"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },

    // oral/hand pussy service actions
    "Rub Pussy":
    {
        "positions": [ "Missionary", "Laid Across On Back", "Laid Across On Stomach", "Mating Press", "Prone Bone", "Sixty-Nine", "From Behind", "Doggy", "Bent Over", "Perched", "Cowgirl", "Reverse Cowgirl", "Kneeling", "Kneeling Over", "Standing", "Standing From Behind", "Lap ride", "Sit On Face", "Oral Service", "Spooning", "Kneeling By Face", "Squatting Before", "Double Decker", "Kneeling Between Thighs", "Against Wall", "Against Wall From Behind", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["tease"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": [],
        "Bottom cum locations": ["on fingers"],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal":  40,
        "Top arousal cap": 300,
        "Bottom arousal cap": 600,
        "act label substitution": ["Bottom", "transgender male", "Rub Front Hole"],
        "Top dialogue tags": ["rubbing pussy"],
        "Bottom dialogue tags": ["pussy rubbed"],
    },
    "Pull Hand To Pussy":  /*Check if needed */
    {
        "positions": [ "Missionary", "Laid Across On Back:Bottom",  "Mating Press:Bottom", "Sixty-Nine", "From Behind", "Doggy:Bottom", "Perched", "Cowgirl", "Reverse Cowgirl", "Kneeling:Bottom", "Kneeling Over:Bottom", "Standing", "Standing From Behind", "Lap ride", "Riding Face:Bottom", "Oral Service:Top", "Spooning:Bottom", "Squatting Before:Top", "Double Decker:Bottom", "Kneeling Between Thighs:Bottom", "Against Wall", "Against Wall From Behind:Top", "Perched Oral Service:Top", "Underneath Oral Service:Top", "Laid Across Oral Service:Top"],
        "action type": ["tease"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 40,
        "Bottom arousal":  10,
        "Bottom arousal cap": 300,
        "act label substitution": ["Top", "transgender male", "Pull Hand To Front Hole"],
    },
    "Finger Pussy": /* Bottom must have a vagina */
    {
        "positions": [ "Missionary", "Laid Across On Back", "Laid Across On Stomach", "Mating Press", "Sixty-Nine", "From Behind", "Doggy", "Perched", "Cowgirl", "Reverse Cowgirl", "Kneeling", "Kneeling Over", "Standing", "Sitting", "Standing From Behind", "Lap ride", "Sit On Face", "Oral Service",  "Spooning", "Kneeling By Face", "Squatting Before", "Double Decker", "Kneeling Between Thighs", "Against Wall", "Against Wall From Behind", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["penetrate"],

        "Top parts": ["Hand"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": [],
        "Bottom cum locations": ["on fingers"],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal":  45,
        "Top arousal cap": 300,
        "remember as": ["fingerbang", "given"],
        "act label substitution": ["Bottom", "transgender male", "Finger Front Hole"],
        "Top dialogue tags": ["fingering pussy"],
        "Bottom dialogue tags": ["pussy fingered"],
    },
    "Finger Pussy(Continue)":
    {
        "positions": [ "Missionary", "Laid Across On Back", "Laid Across On Stomach", "Mating Press", "Sixty-Nine", "From Behind", "Doggy", "Perched", "Cowgirl", "Reverse Cowgirl", "Kneeling", "Kneeling Over", "Standing", "Standing From Behind", "Lap ride", "Reverse Lap ride", "Sit On Face", "Oral Service",  "Spooning", "Kneeling By Face", "Squatting Before", "Double Decker", "Kneeling Between Thighs", "Against Wall", "Against Wall From Behind", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["continue"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": [],
        "Bottom cum locations": ["on fingers"],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal":  45,
        "Top arousal cap": 300,
        "remember as": ["fingerbang", "given"],
        "act label substitution": ["Bottom", "transgender male", "Finger Front Hole"],
        "Top dialogue tags": ["fingering pussy"],
        "Bottom dialogue tags": ["pussy fingered"],
    },
    "Stop Fingering":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },
    "Pull Off Of Finger":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Vagina"],
        "Bottom parts": ["Hand"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },

    "Rub Clit":
    {
        "positions": [ "Missionary", "Laid Across On Back", "Laid Across On Stomach", "Mating Press", "Sixty-Nine", "From Behind", "Doggy", "Bent Over", "Perched", "Cowgirl", "Reverse Cowgirl", "Kneeling", "Kneeling Over", "Standing", "Standing From Behind", "Lap ride", "Sit On Face", "Oral Service", "Spooning", "Kneeling By Face", "Squatting Before", "Double Decker", "Kneeling Between Thighs", "Against Wall", "Against Wall From Behind", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["tease"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Clitoris"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 50,
        "Top arousal cap": 300,
        "remember as": ["fingerbang", "given"],
        "act label substitution": ["Bottom", "transgender male", "Rub T-Dick"],
        "Top dialogue tags": ["rubbing clit"],
        "Bottom dialogue tags": ["clit rubbed"],
        coexist: true,
    },
    "Lick Pussy":
    {
        "positions": ["Sit On Face", "Sixty-Nine", "Kneeling", "Kneeling Over", "Oral Service", "Squatting Before", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["tease"],
        "Top parts": ["Tongue"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": [],
        "Bottom cum locations": ["on tongue"],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal":  50,
        "Top arousal cap": 300,
        "remember as": ["cunnilingus", "given"],
        "act label substitution": ["Bottom", "transgender male", "Lick Front Hole"],
        "Top dialogue tags": ["licking pussy"],
        "Bottom dialogue tags": ["pussy licked"],
        coexist: true,
    },
    "Suck Clit":
    {
        "positions": [ "Sit On Face", "Sixty-Nine", "Kneeling", "Kneeling Over", "Oral Service", "Squatting Before", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["tease"],
        "Top parts": ["Mouth"],
        "Bottom parts": ["Clitoris"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 60,
        "Top arousal cap": 300,
        "remember as": ["cunnilingus", "given"],
        "act label substitution": ["Bottom", "transgender male", "Suck T-Dick"],
        "Top dialogue tags": ["licking pussy"],
        "Bottom dialogue tags": ["pussy licked"],
        coexist: true,
    },
    "Ride Face": /*Check if redundant */
    {
        "positions": [ "Riding Face:Top", "Kneeling:Top", "Kneeling Over:Top", "Oral Service:Top", "Squatting Before:Top", "Perched Oral Service:Top", "Underneath Oral Service:Top", "Laid Across Oral Service:Top"],
        "action type": ["tease"],
        "Top parts": ["Vagina"],
        "Bottom parts": ["Mouth"],
        "Top cum locations": [],
        "Bottom cum locations": ["in mouth"],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 50,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
        "remember as": ["cunnilingus", "received"],
        "Top dialogue tags": ["Sit On Face"],
        "Bottom dialogue tags": ["face ridden"],
    },
    // oral/hand cock service actions
    "Lick Asshole":
    {
        "positions": [ "Sixty-Nine", "Kneeling", "Kneeling Over", "Oral Service", "Kneeling By Face", "Squatting Before", "Sit On Face", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["tease"],
        "Top parts": ["Tongue"],
        "Bottom parts": ["Asshole"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 40,
        "Top arousal cap": 300,
        "Bottom part uncovered": true,
        "remember as": ["rimjob", "given"],
        "Top dialogue tags": ["licking ass"],
        "Bottom dialogue tags": ["ass licked"],
    },
    "Lick Cock":
    {
        "positions": [ "Sixty-Nine", "Kneeling", "Kneeling Over", "Oral Service", "Kneeling By Face", "Squatting Before", "Sit On Face", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["tease"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Tongue"],
        "Top cum locations": ["on tongue"],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 15,
        "Bottom arousal": 50,
        "Top arousal cap": 300,
        "Top dialogue tags": ["licking cock"],
        "Bottom dialogue tags": ["cock licked"],
    },
    "Rub Cock On Face": /* Check if necessary */
    {
        "positions": [ "Sixty-Nine", "Kneeling", "Kneeling Over", "Oral Service", "Kneeling By Face", "Squatting Before", "Sit On Face", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["tease"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Mouth"],
        "Top cum locations": ["on face"],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 40,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
        "Top dialogue tags": ["rubbing cock on face"],
        "Bottom dialogue tags": ["face rubbed by cock"],
    },
    "Rub Cock Against Hand": /* Check if necessary */
    {
        "positions": [ "Sixty-Nine", "Kneeling", "Kneeling Over", "Standing", "Lap ride", "Oral Service", "Perched", "Spooning", "Kneeling By Face", "Squatting Before", "Double Decker", "Sit On Face", "Against Wall", "Against Wall From Behind", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["tease"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Hand"],
        "Top cum locations": ["on hand"],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 40,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300
    },
    "Lick Foot": /* You lick their foot*/
    {
        "positions": [ "Sixty-Nine", "Missionary", "Kneeling", "Kneeling Over", "Perched", "Laid Across On Back", "Laid Across On Stomach"],
        "action type": ["tease"],
        "Top parts": ["Mouth"],
        "Bottom parts": ["Feet"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 15,
        "Bottom arousal": 15,
        "Top arousal cap": 300,
        "Bottom arousal cap": 300,
    },

    "Grip Cock": /* You grip their cock */
    {
        "positions": [ "Sixty-Nine:Bottom", "Lap ride:Bottom", "Reverse Lap ride:Bottom", "Kneeling:Bottom", "Kneeling Over:Bottom", "Standing:Bottom", "Oral Service:Bottom", "Spooning:Bottom", "Kneeling By Face:Bottom", "Squatting Before:Bottom", "Double Decker:Bottom", "Kneeling Between Thighs:Bottom", "Riding Face:Bottom", "Perched:Bottom", "Against Wall:Bottom", "Against Wall From Behind:Bottom", "Perched Oral Service:Bottom", "Underneath Oral Service:Bottom", "Laid Across Oral Service:Bottom"],
        "action type": ["penetrate"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Hand"],

        "Top cum locations": ["on hand"],
        "Bottom cum locations": [],

        "masturbation": true,
        "take virginity": [],
        "Top arousal": 20,
        "Bottom arousal": 10,
        "Top arousal cap": 300,
        "remember as": ["handjob", "given"],
        "Top dialogue tags": ["giving handjob"],
        "Bottom dialogue tags": ["receiving handjob"],
    },
    "Wrap Hand Around Cock": /* they wrap their hand around your penis */
    {
        "positions": [ "Sixty-Nine:Top", "Lap ride:Top", "Reverse Lap ride:Top", "Kneeling:Top", "Kneeling Over:Top", "Standing:Top", "Oral Service:Top", "Spooning:Top", "Kneeling By Face:Top", "Squatting Before:Top", "Double Decker:Top", "Riding Face:Top", "Perched:Top", "Against Wall:Top", "Against Wall From Behind:Top", "Perched Oral Service:Top", "Underneath Oral Service:Top", "Laid Across Oral Service:Top"],
        "action type": ["penetrate"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Hand"],

        "Top cum locations": ["on hand"],
        "Bottom cum locations": [],

        "masturbation": false,
        "take virginity": [],
        "Top arousal": 20,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
        "remember as": ["handjob", "received"],
    },
    "Pump Shaft": /*Bottom pumps their shaft */
    {
        "positions": [ "Sixty-Nine:Bottom", "Lap ride:Bottom", "Reverse Lap ride:Bottom", "Kneeling:Bottom", "Kneeling Over:Bottom", "Standing:Bottom", "Oral Service:Bottom", "Spooning:Bottom", "Kneeling By Face:Bottom", "Squatting Before:Bottom", "Double Decker:Bottom", "Kneeling Between Thighs:Bottom", "Riding Face:Bottom", "Perched:Bottom", "Against Wall:Bottom", "Against Wall From Behind:Bottom", "Perched Oral Service:Bottom", "Underneath Oral Service:Bottom", "Laid Across Oral Service:Bottom"],
        "action type": ["continue"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Penis"],

        "Top cum locations": [],
        "Bottom cum locations": ["on hand"],

        "masturbation": true,
        "take virginity": [],
        "Top arousal": 50,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
        "Top dialogue tags": ["giving handjob"],
        "Bottom dialogue tags": ["receiving handjob"],
    },
    "Fuck Fist": /* Top fucks their fist */
    {
        "positions": [ "Sixty-Nine:Top", "Lap ride:Top", "Reverse Lap ride:Top", "Kneeling:Top", "Kneeling Over:Top", "Standing:Top", "Oral Service:Top", "Spooning:Top", "Kneeling By Face:Top", "Squatting Before:Top", "Double Decker:Top", "Kneeling Between Thighs:Top", "Riding Face:Top", "Perched:Top", "Against Wall:Top", "Against Wall From Behind:Top", "Perched Oral Service:Top", "Underneath Oral Service:Top", "Laid Across Oral Service:Top"],
        "action type": ["continue"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Hand"],
        "Top cum locations": ["on hand"],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 50,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
    },
    "Tease Tip": /*Either one teases the tip */
    {
        "positions": [ "Sixty-Nine","Lap ride", "Reverse Lap ride", "Kneeling", "Kneeling Over", "Standing", "Oral Service", "Spooning", "Kneeling By Face", "Squatting Before", "Double Decker", "Kneeling Between Thighs", "Sit On Face", "Perched", "Against Wall", "Against Wall From Behind", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["continue"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Penis"],
        "Top cum locations": [],
        "Bottom cum locations": ["on hand"],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 30,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
        "Top dialogue tags": ["giving handjob"],
        "Bottom dialogue tags": ["receiving handjob"],
    },

    "Play with Foreskin": { /* Right now only works if the Bottom is uncut? */
        "positions": [ "Sixty-Nine", "Kneeling", "Lap ride", "Reverse Lap ride","Kneeling Over", "Standing", "Oral Service", "Spooning", "Kneeling By Face", "Squatting Before", "Double Decker", "Kneeling Between Thighs", "Sit On Face", "Perched", "Against Wall", "Against Wall From Behind", "Perched Oral Service", "Underneath Oral Service", "Laid Across Oral Service"],
        "action type": ["continue"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Penis"],
        "Top genitaltype": [],
        "Bottom genitaltype": ["Uncut"],
        "Top cum locations": [],
        "Bottom cum locations": ["on hand"],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 30,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
        "Top dialogue tags": ["giving handjob"],
        "Bottom dialogue tags": ["receiving handjob"]
    },

    "Release Cock":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Penis"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0
    },
    "Tug Cock Free":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Hand"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0
    },


    "Grip Cock With Feet": /* you grip their cock with your feet. */
    {
        "positions": [ "Missionary:Bottom", "Kneeling:Bottom", "Perched:Bottom", "Laid Across On Back:Bottom"],
        "action type": ["penetrate"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Feet"],
        "Top cum locations": ["on feet"],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 20,
        "Top arousal cap": 300,
        "remember as": ["footjob", "given"],
        "Top dialogue tags": ["giving footjob"],
        "Bottom dialogue tags": ["receiving footjob"],
    },
    "Pull Feet Around Cock": /* they pull their feet around your cock */
    {
        "positions": [ "Missionary:Top", "Kneeling:Top", "Perched:Top", "Laid Across On Back:Top"],
        "action type": ["penetrate"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Feet"],
        "Top cum locations": ["on feet"],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 20,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
        "remember as": ["footjob", "received"],
    },
     "Stroke Shaft With Feet": /* You stroke their cock with your feet */
    {
        "positions": [ "Missionary:Bottom", "Kneeling:Bottom", "Perched:Bottom", "Laid Across On Back:Bottom"],
        "action type": ["continue"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Feet"],
        "Top cum locations": ["on feet"],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 60,
        "Top arousal cap": 300,
        "Top dialogue tags": ["giving footjob"],
        "Bottom dialogue tags": ["receiving footjob"],
    },
    "Fuck Feet": /*You fuck their feet with your cock. */
    {
        "positions": [ "Missionary:Top", "Kneeling:Top", "Perched:Top", "Laid Across On Back:Top"],
        "action type": ["continue"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Feet"],
        "Top cum locations": ["on feet"],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 50,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
    },
    "Tease Cock With Feet": /* Check if necessary */
    {
        "positions": [ "Missionary", "Laid Across On Back", "Kneeling", "Perched"],
        "action type": ["continue"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Feet"],
        "Top cum locations": ["on feet"],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 30,
        "Top arousal cap": 300,
    },
    "Rub Cock Against Feet": /*You rub your cock against their feet */
    {
        "positions": [ "Missionary", "Laid Across On Back", "Kneeling"],
        "action type": ["continue"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Feet"],
        "Top cum locations": ["on feet"],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 40,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
    },
        "Release Cock From Feet":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Feet"],
        "Bottom parts": ["Penis"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0
    },
    "Tug Cock Free Of Feet":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Feet"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0
    },

    "Rub Pussy With Feet": /* you rub their pussy with your feet. */
    {
        "positions": [ "Missionary:Bottom", "Kneeling:Bottom", "Perched:Bottom", "Laid Across On Back:Bottom"],
        "action type": ["penetrate"],
        "Top parts": ["Feet"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": [],
        "Bottom cum locations": ["on feet"],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 20,
        "Top arousal cap": 300,
        "remember as": ["footjob", "given"],
        "Top dialogue tags": ["giving footjob"],
        "Bottom dialogue tags": ["receiving footjob"],
    },
    "Pull Feet To Pussy": /* they pull their feet to your pussy */
    {
        "positions": [ "Missionary:Top", "Kneeling:Top", "Perched:Top", "Laid Across On Back:Top"],
        "action type": ["penetrate"],
        "Top parts": ["Vagina"],
        "Bottom parts": ["Feet"],
        "Top cum locations": [],
        "Bottom cum locations": ["on feet"],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 20,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
        "remember as": ["footjob", "received"],
        "act label substitution": ["Top", "transgender male", "Pull Feet To Front Hole"],
    },
    "Stroke Pussy With Feet": /* You stroke their pussy with your feet */
    {
        "positions": [ "Missionary:Bottom", "Kneeling:Bottom", "Perched:Bottom", "Laid Across On Back:Bottom"],
        "action type": ["continue"],
        "Top parts": ["Feet"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": [],
        "Bottom cum locations": ["on feet"],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 60,
        "Top arousal cap": 300,
        "act label substitution": ["Bottom", "transgender male", "Stroke Front Hole With Feet"],
        "Top dialogue tags": ["giving footjob"],
        "Bottom dialogue tags": ["receiving footjob"],
    },
    "Tease Pussy With Feet": /* You tease their pussy with your feet.*/
    {
        "positions": [ "Missionary", "Laid Across On Back", "Kneeling"],
        "action type": ["continue"],
        "Top parts": ["Feet"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": [],
        "Bottom cum locations": ["on feet"],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 30,
        "Top arousal cap": 300,
        "act label substitution": ["Bottom", "transgender male", "Tease Front Hole With Feet"],
    },
    "Rub Pussy Against Feet": /* You rub your pussy against their feet.*/
    {
        "positions": [ "Missionary", "Laid Across On Back", "Kneeling"],
        "action type": ["continue"],
        "Top parts": ["Vagina"],
        "Bottom parts": ["Feet"],
        "Top cum locations": [],
        "Bottom cum locations": ["on feet"],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 40,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
        "act label substitution": ["Top", "transgender male", "Rub Front Hole Against Feet"],
    },
    "Rub Against Feet": /*You rub your pussy against their feet */
    {
        "positions": [ "Missionary:Top", "Kneeling:Top", "Perched:Top", "Laid Across On Back:Top"],
        "action type": ["continue"],
        "Top parts": ["Vagina"],
        "Bottom parts": ["Feet"],
        "Top cum locations": ["on feet"],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 50,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
    },
    "Move Feet Away From Pussy":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Feet"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
        "act label substitution": ["Bottom", "transgender male", "Move Feet Away From Front Hole"],
    },
    "Pull Away From Feet":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Vagina"],
        "Bottom parts": ["Feet"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0
    },


    "Take Cock Between Lips": /* You take their cock in your mouth. */
    {
        "positions": [ "Sixty-Nine:Bottom", "Kneeling:Bottom", "Kneeling Over:Bottom", "Oral Service:Bottom", "Kneeling By Face:Bottom", "Squatting Before:Bottom", "Riding Face:Bottom", "Perched Oral Service:Bottom", "Underneath Oral Service:Bottom", "Laid Across Oral Service:Bottom","Straddling Chest:Bottom"],
        "action type": ["penetrate"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Mouth"],
        "Top cum locations": ["in mouth"],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": ["Mouth"],
        "Top arousal": 10,
        "Bottom arousal": 25,
        "Top arousal cap": 300,
        "remember as": ["blowjob", "given"],
        "Top dialogue tags": ["giving blowjob"],
        "Bottom dialogue tags": ["receiving blowjob"],
    },
    "Enter Mouth": /* They put your cock in their mouth */
    {
        "positions": [ "Sixty-Nine:Top", "Kneeling:Top", "Kneeling Over:Top", "Oral Service:Top", "Kneeling By Face:Top", "Squatting Before:Top", "Riding Face:Top", "Perched Oral Service:Top", "Underneath Oral Service:Top", "Laid Across Oral Service:Top","Straddling Chest:Top"],
        "action type": ["penetrate"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Mouth"],
        "Top cum locations": ["in mouth"],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": ["Mouth"],
        "Top arousal": 25,
        "Bottom arousal": 10,
        "Bottom arousal cap": 300,
        "remember as": ["blowjob", "received"],
        "Top dialogue tags": ["taking blowjob"],
        "Bottom dialogue tags": ["giving blowjob"],
    },
    "Suck Cock": /*You suck their cock */
    {
        "positions": [ "Kneeling:Bottom", "Kneeling Over:Bottom", "Oral Service:Bottom", "Kneeling By Face:Bottom", "Squatting Before:Bottom", "Riding Face:Bottom", "Perched Oral Service:Bottom", "Underneath Oral Service:Bottom", "Laid Across Oral Service:Bottom"],
        "action type": ["continue"],
        "Top parts": ["Mouth"],
        "Bottom parts": ["Penis"],
        "Top cum locations": ["in mouth"],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal": 55,
        "Top arousal cap": 300,
        "Top dialogue tags": ["giving blowjob"],
        "Bottom dialogue tags": ["receiving blowjob"],
    },
    "Fuck Mouth": /*You fuck their mouth with your cock */
    {
        "positions": [  "Kneeling:Top", "Kneeling Over:Top", "Oral Service:Top", "Kneeling By Face:Top", "Squatting Before:Top", "Riding Face:Top", "Perched Oral Service:Top", "Underneath Oral Service:Top", "Laid Across Oral Service:Top"],
        "action type": ["continue"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Mouth"],
        "Top cum locations": ["in mouth"],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Bottom arousal": 10,
        "Top arousal": 50,
        "Bottom arousal cap": 300,
        "Top dialogue tags": ["taking blowjob"],
        "Bottom dialogue tags": ["giving blowjob"],
    },
    "Pull Out Of Mouth":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Mouth"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },
    "Pull Mouth Off Of Cock":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Mouth"],
        "Bottom parts": ["Penis"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },

    "Suck Each Other Off": /* Mutual cocksucking */
    {
        "positions": [ "Sixty-Nine"],
        "action type": ["penetrate"],
        "Top parts": ["Penis", "Mouth"],
        "Bottom parts": ["Mouth", "Penis"],
        "Top parts mode": "all",
        "Bottom parts mode": "all",
        "Top cum locations": ["in mouth"],
        "Bottom cum locations": ["in mouth"],
        "masturbation": false,
        "take virginity": [],
        "Bottom arousal": 50,
        "Top arousal": 50,
        "Bottom arousal cap": 300,
        "Top dialogue tags": ["sucking each other"],
        "Bottom dialogue tags": ["sucking each other"],
        equal: true,
    },
    "Eat Each Other Out": /* Mutual eat each other's vagina */
    {
        "positions": ["Sixty-Nine"],
        "action type": ["penetrate"],
        "Top parts": ["Vagina", "Mouth"],
        "Bottom parts": ["Mouth", "Vagina"],
        "Top parts mode": "all",
        "Bottom parts mode": "all",
        "Top cum locations": ["in mouth"],
        "Bottom cum locations": ["in mouth"],
        "masturbation": false,
        "take virginity": [],
        "Bottom arousal": 50,
        "Top arousal": 50,
        "Bottom arousal cap": 300,
        equal: true,
        
    },
    "Suck And Lick Each Other": /* Mutual cock and pussy suck */
    {
        positions: ["Sixty-Nine"],
        "action type": ["penetrate"],
        "Top parts": ["Penis", "Mouth"],
        "Bottom parts": ["Mouth", "Vagina"],
        "Top parts mode": "all",
        "Bottom parts mode": "all",
        "Top cum locations": ["in mouth"],
        "Bottom cum locations": ["in mouth"],
        "masturbation": false,
        "take virginity": [],
        "Bottom arousal": 50,
        "Top arousal": 50,
        "Bottom arousal cap": 300,
        equal: true,
        
    },
    "Lick And Suck Each Other": /*Mutual pussy and cock suck */
    {
        positions: ["Sixty-Nine"],
        "action type": ["penetrate"],
        "Top parts": ["Vagina", "Mouth"],
        "Bottom parts": ["Mouth", "Penis"],
        "Top parts mode": "all",
        "Bottom parts mode": "all",
        "Top cum locations": ["in mouth"],
        "Bottom cum locations": ["in mouth"],
        "masturbation": false,
        "take virginity": [],
        "Bottom arousal": 50,
        "Top arousal": 50,
        "Bottom arousal cap": 300,
        equal: true,
    },


    "Tease Pussy With Cock": /* You tease their pussy with your cock */
    {
        "positions": [ "Missionary:Top", "Mating Press:Top", "Prone Bone:Top", "From Behind:Top", "Doggy:Top", "Bent Over:Top", "Cowgirl:Top", "Reverse Cowgirl:Top", "Standing:Top", "Standing From Behind:Top", "Lap ride:Top", "Spooning:Top", "Double Decker:Top", "Kneeling Between Thighs:Top", "Perched:Top", "Against Wall:Top", "Against Wall From Behind:Top", "Laid Across On Back:Top", "Laid Across On Stomach:Top"],
        "action type": ["tease"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": ["on pussy"],
        "Bottom cum locations": ["on cock"],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 25,
        "Bottom arousal": 25,
        "act label substitution": ["Bottom", "transgender male", "Tease Front Hole With Cock"],
        "Top dialogue tags": ["teasing pussy with cock"],
        "Bottom dialogue tags": ["pussy teased by cock"],
    },
    "Cocktease With Pussy": /*You tease their cock with your pussy */
    {
        "positions": [ "Missionary:Bottom", "Mating Press:Bottom", "Prone Bone:Bottom", "From Behind:Bottom", "Doggy:Bottom", "Bent Over:Bottom", "Cowgirl:Bottom", "Reverse Cowgirl:Bottom", "Standing:Bottom", "Standing From Behind:Bottom", "Lap ride:Bottom", "Spooning:Bottom", "Double Decker:Bottom", "Kneeling Between Thighs:Bottom", "Perched:Bottom", "Against Wall:Bottom", "Against Wall From Behind:Bottom", "Laid Across On Back:Bottom", "Laid Across On Stomach:Bottom"],
        "action type": ["tease"],
        "Top parts": ["Vagina"],
        "Bottom parts": ["Penis"],
        "Top cum locations": ["on cock"],
        "Bottom cum locations": ["on pussy"],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 25,
        "Bottom arousal": 25,
        "act label substitution": ["Top", "transgender male", "Cocktease With Front Hole"],
        "Top dialogue tags": ["teasing cock with pussy"],
        "Bottom dialogue tags": ["cock teased by pussy"],
    },

   
    "Enter Pussy": /* You enter their pussy with your cock */
    {
        "positions": [ "Missionary:Top", "Mating Press:Top","Lap ride:Top", "Reverse Lap ride:Top", "Prone Bone:Top", "From Behind:Top", "Doggy:Top", "Bent Over:Top", "Cowgirl:Top", "Reverse Cowgirl:Top", "Standing:Top", "Standing From Behind:Top", "Lap ride:Top", "Reverse Lap ride:Top", "Spooning:Top", "Double Decker:Top", "Kneeling Between Thighs:Top", "Perched:Top", "Against Wall:Top", "Against Wall From Behind:Top", "Laid Across On Back:Top", "Laid Across On Stomach:Top","Scissor:Top"],
        "action type": ["penetrate"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": ["in pussy"],
        "Bottom cum locations": ["on cock"],
        "masturbation": false,
        "take virginity": ["Penis", "Vagina"],
        "Top arousal": 50,
        "Bottom arousal": 50,
        "remember as": ["pussy-fucking", "received"],
        "act label substitution": ["Bottom", "transgender male", "Enter Front Hole"],
    },
    "Push Cock In": /* They enter your pussy with their cock */
    {
        "positions": [ "Missionary:Bottom", "Lap ride:Bottom", "Reverse Lap ride:Bottom", "Mating Press:Bottom", "Prone Bone:Bottom", "From Behind:Bottom", "Doggy:Bottom", "Bent Over:Bottom", "Cowgirl:Bottom", "Reverse Cowgirl:Bottom", "Standing:Bottom", "Standing From Behind:Bottom", "Spooning:Bottom", "Double Decker:Bottom", "Kneeling Between Thighs:Bottom", "Perched:Bottom", "Against Wall:Bottom", "Against Wall From Behind:Bottom", "Laid Across On Back:Bottom", "Laid Across On Stomach:Bottom","Scissor:Bottom"],
        "action type": ["penetrate"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": ["on cock"],
        "Bottom cum locations": ["in pussy"],
        "masturbation": false,
        "take virginity": ["Penis", "Vagina"],
        "Top arousal": 50,
        "Bottom arousal": 50,
        "remember as": ["pussy-fucking", "given"],
    },
    "Fuck Pussy": /* You continue to fuck their pussy with your cock */
    {
        "positions": [ "Missionary:Top", "Mating Press:Top", "Prone Bone:Top", "From Behind:Top", "Doggy:Top", "Bent Over:Top", "Cowgirl:Top", "Reverse Cowgirl:Top", "Standing:Top", "Standing From Behind:Top", "Lap ride:Top","Reverse Lap ride:Top", "Spooning:Top", "Double Decker:Top", "Kneeling Between Thighs:Top", "Perched:Top", "Against Wall:Top", "Against Wall From Behind:Top", "Laid Across On Back:Top", "Laid Across On Stomach:Top","Scissor:Top"],
        "action type": ["continue"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": ["in pussy"],
        "Bottom cum locations": ["on cock"],
        "masturbation": false,
        "Top arousal": 50,
        "Bottom arousal": 50,
        "act label substitution": ["Bottom", "transgender male", "Fuck Front Hole"],
        "Top dialogue tags": ["fucking pussy"],
        "Bottom dialogue tags": ["pussy fucked"],
    },
    "Take Cock": /*They coninute to fuck your pussy with their cock */
    {
        "positions": [ "Missionary:Bottom", "Mating Press:Bottom", "Prone Bone:Bottom", "From Behind:Bottom", "Doggy:Bottom", "Bent Over:Bottom", "Standing:Bottom", "Standing From Behind:Bottom",  "Spooning:Bottom", "Double Decker:Bottom", "Kneeling Between Thighs:Bottom", "Perched:Bottom", "Against Wall:Bottom", "Against Wall From Behind:Bottom", "Laid Across On Back:Bottom", "Laid Across On Stomach:Bottom","Scissor:Bottom"],
        "action type": ["continue"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": ["on cock"],
        "Bottom cum locations": ["in pussy"],
        "masturbation": false,
        "Top arousal": 50,
        "Bottom arousal": 50,
        "Top dialogue tags": ["fucking cock"],
        "Bottom dialogue tags": ["cock fucked"],
    },
    "Hump Back": /* Tease option for taking cock? */
    {
        "positions": [ "Missionary:Bottom", "Mating Press:Bottom", "Prone Bone:Bottom", "From Behind:Bottom", "Doggy:Bottom", "Bent Over:Bottom", "Standing:Bottom", "Standing From Behind:Bottom", "Spooning:Bottom", "Double Decker:Bottom", "Kneeling Between Thighs:Bottom", "Perched:Bottom", "Against Wall:Bottom", "Against Wall From Behind:Bottom", "Laid Across On Back:Bottom", "Laid Across On Stomach:Bottom"],
        "action type": ["continue"],
        "Top parts": ["Vagina"],
        "Bottom parts": ["Penis"],
        "Top cum locations": ["on cock"],
        "Bottom cum locations": ["in pussy"],
        "masturbation": false,
        "Top arousal": 60,
        "Bottom arousal": 60,
        "Top dialogue tags": ["fucking cock"],
        "Bottom dialogue tags": ["cock fucked"],
    },
    "Ride Cock": /* Bottom vaginal option when the Bottom is on Top */
    {
        "positions": [ "Cowgirl:Bottom", "Reverse Cowgirl:Bottom", "Lap ride:Bottom", "Reverse Lap ride:Bottom"],
        "action type": ["continue"],
        "Top parts": ["Vagina"],
        "Bottom parts": ["Penis"],
        "Top cum locations": ["on cock"],
        "Bottom cum locations": ["in pussy"],
        "masturbation": false,
        "Top arousal": 60,
        "Bottom arousal": 60,
        "Top dialogue tags": ["riding cock"],
        "Bottom dialogue tags": ["cock ridden"],
    },
    "Pull Out":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },
    "Pull Off":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Vagina"],
        "Bottom parts": ["Penis"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },


    "Frot":
    {
        "positions": [ "Missionary", "Lap ride", "Standing", "Kneeling Between Thighs", "Perched", "Against Wall", "Laid Across On Back","Scissor"],
        "action type": ["penetrate"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Penis"],
        "Top cum locations": ["on penis"],
        "Bottom cum locations": ["on penis"],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 40,
        "Bottom arousal": 40,
        "Top dialogue tags": ["frotting"],
        "Bottom dialogue tags": ["frotting"],
        "remember as": ["frotted"],
    },
    "Continue Frotting":
    {
        "positions": [ "Missionary", "Lap ride", "Standing", "Kneeling Between Thighs", "Perched", "Against Wall", "Laid Across On Back","Scissor"],
        "action type": ["continue"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Penis"],
        "Top cum locations": ["on penis"],
        "Bottom cum locations": ["on penis"],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 40,
        "Bottom arousal": 40,
        "Top dialogue tags": ["frotting"],
        "Bottom dialogue tags": ["frotting"],
        "remember as": ["frotted"],
    },
    "Stop Frotting":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Penis"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },

    "Trib":
    {
        "positions": [ "Missionary", "Laid Across On Back","Scissor"],
        "action type": ["tease"],
        "Top parts": ["Vagina"],
        "Bottom parts": ["Vagina"],
        "Top cum locations": ["on pussy"],
        "Bottom cum locations": ["on pussy"],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 40,
        "Bottom arousal": 40,
        "Top dialogue tags": ["tribbing"],
        "Bottom dialogue tags": ["tribbing"],
        "remember as": ["tribbed"],
    },
    "Tease Ass With Cock":
    {
        "positions": [ "Missionary:Top", "Prone Bone:Top", "Mating Press:Top", "From Behind:Top", "Doggy:Top", "Bent Over:Top", "Cowgirl:Top", "Reverse Cowgirl:Top", "Standing From Behind:Top", "Reverse Lap ride:Top", "Spooning:Top", "Double Decker:Top", "Against Wall From Behind:Top", "Laid Across On Back:Top", "Laid Across On Stomach:Top"],
        "action type": ["tease"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Ass"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 50,
        "Bottom arousal": 25,
        "Top dialogue tags": ["teasing ass with cock"],
        "Bottom dialogue tags": ["ass teased with cock"],
    },
    "Cocktease With Ass":
    {
        "positions": [ "Missionary:Bottom", "Prone Bone:Bottom", "Mating Press:Bottom", "From Behind:Bottom", "Doggy:Bottom", "Bent Over:Bottom", "Cowgirl:Bottom", "Reverse Cowgirl:Bottom", "Standing From Behind:Bottom", "Reverse Lap ride:Bottom", "Spooning:Bottom", "Double Decker:Bottom", "Against Wall From Behind:Bottom", "Laid Across On Back:Bottom", "Laid Across On Stomach:Bottom"],
        "action type": ["tease"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Asshole"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 25,
        "Bottom arousal": 50,
        "Top dialogue tags": ["teasing cock with ass"],
        "Bottom dialogue tags": ["cock teased with ass"],
    },
    "Rub Butthole": /* You rub your fingers on their ass, might not be Top specific? */
    {
        "positions": [ "Missionary:Bottom", "Lap ride:Bottom", "Reverse Lap ride:Bottom", "Prone Bone:Bottom", "Mating Press:Top", "Sixty-Nine:Bottom", "From Behind:Top", "Doggy:Top", "Bent Over:Top", "Cowgirl:Bottom", "Reverse Cowgirl:Bottom", "Kneeling:Bottom", "Kneeling Over:Bottom", "Standing:Bottom", "Standing From Behind:Top", "Oral Service:Bottom", "Spooning:Top", "Double Decker:Top", "Against Wall From Behind:Top", "Perched Oral Service:Bottom", "Underneath Oral Service:Bottom", "Laid Across On Back:Top", "Laid Across On Stomach:Top", "Laid Across Oral Service:Bottom","Sitting"],
        "action type": ["tease"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Asshole"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 10,
        "Bottom arousal":  30,
        "Top arousal cap": 300,
        "Top dialogue tags": ["rubbing anus"],
        "Bottom dialogue tags": ["anus rubbed"],
    },
    

    "Enter Ass": /* You enter their ass*/
    {
        "positions": [ "Missionary:Top", "Prone Bone:Top", "Lap ride:Top", "Reverse Lap ride:Top", "Mating Press:Top", "From Behind:Top", "Doggy:Top", "Bent Over:Top", "Cowgirl:Top", "Reverse Cowgirl:Top", "Standing From Behind:Top", "Spooning:Top", "Double Decker:Top","Against Wall: Top", "Against Wall From Behind:Top", "Laid Across On Back:Top", "Laid Across On Stomach:Top"],
        "action type": ["penetrate"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Asshole"],

        "Top cum locations": ["in ass"],
        "Bottom cum locations": [],

        "masturbation": false,
        "take virginity": ["Penis", "Asshole"],
        "Top arousal": 50,
        "Bottom arousal": 10,
        "remember as": ["ass-fucking", "received"],
        "blocked traits": {
            Top: [],   // if the *Top* has any of these traits, block
            Bottom:  ["Will Not Bottom"]                 // if the *Bottom* has any of these traits, block
        }
    },
    "Push Cock In Ass":
    {
        "positions": [ "Missionary:Bottom", "Lap ride:Bottom", "Reverse Lap ride:Bottom", "Prone Bone:Bottom", "Mating Press:Bottom", "From Behind:Bottom", "Doggy:Bottom", "Bent Over:Bottom", "Cowgirl:Bottom", "Reverse Cowgirl:Bottom", "Standing From Behind:Bottom", "Spooning:Bottom", "Double Decker:Bottom","Against Wall:Bottom", "Against Wall From Behind:Bottom", "Laid Across On Back:Bottom", "Laid Across On Stomach:Bottom"],
        "action type": ["penetrate"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Asshole"],
        "Top cum locations": [],
        "Bottom cum locations": ["in ass"],
        "masturbation": false,
        "take virginity": ["Penis", "Asshole"],
        "Top arousal": 10,
        "Bottom arousal": 50,
        "remember as": ["ass-fucking", "given"],
        "blocked traits": {
            Top: ["Will Not Top"],   // if the *Top* has any of these traits, block
            Bottom:  []                 // if the *Bottom* has any of these traits, block
        }
    },
    "Fuck Ass":
    {
        "positions": [ "Missionary:Top", "Lap ride:Top", "Reverse Lap ride:Top","Prone Bone:Top", "Mating Press:Top", "From Behind:Top", "Doggy:Top", "Bent Over:Top", "Cowgirl:Top", "Reverse Cowgirl:Top", "Standing From Behind:Top", "Spooning:Top", "Double Decker:Top", "Against Wall From Behind:Top", "Laid Across On Back:Top", "Laid Across On Stomach:Top"],
        "action type": ["continue"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Asshole"],
        "Top cum locations": ["in ass"],
        "Bottom cum locations": [],
        "masturbation": false,
        "Top arousal": 50,
        "Bottom arousal": 40,
        "Top dialogue tags": ["fucking ass"],
        "Bottom dialogue tags": ["ass fucked"],
    },
    "Take Cock In Ass":
    {
        "positions": [ "Missionary:Bottom","Lap ride:Bottom", "Reverse Lap ride:Bottom", "Prone Bone:Bottom", "Mating Press:Bottom", "From Behind:Bottom", "Doggy:Bottom", "Bent Over:Bottom", "Cowgirl:Bottom", "Reverse Cowgirl:Bottom", "Standing From Behind:Bottom", "Spooning:Bottom", "Double Decker:Bottom", "Against Wall From Behind:Bottom", "Laid Across On Back:Bottom", "Laid Across On Stomach:Bottom"],
        "action type": ["continue"],
        "Top parts": ["Asshole"],
        "Bottom parts": ["Penis"],
        "Top cum locations": ["in ass"],
        "Bottom cum locations": [],
        "masturbation": false,
        "Top arousal": 40,
        "Bottom arousal": 50,
        "Top dialogue tags": ["fucking with ass"],
        "Bottom dialogue tags": ["fucked with ass"],
    },
    "Hump Ass Back":
    {
        "positions": [ "Missionary:Bottom", "Prone Bone:Bottom", "Mating Press:Bottom", "From Behind:Bottom", "Doggy:Bottom", "Bent Over:Bottom", "Cowgirl:Bottom", "Reverse Cowgirl:Bottom", "Standing From Behind:Bottom", "Spooning:Bottom", "Double Decker:Bottom", "Against Wall From Behind:Bottom", "Laid Across On Back:Bottom", "Laid Across On Stomach:Bottom"],
        "action type": ["continue"],
        "Top parts": ["Asshole"],
        "Bottom parts": ["Penis"],
        "Top cum locations": ["in ass"],
        "Bottom cum locations": [],
        "masturbation": false,
        "Top arousal": 45,
        "Bottom arousal": 55,
        "Top dialogue tags": ["fucking with ass"],
        "Bottom dialogue tags": ["fucked with ass"],
    },
    "Pull Out Of Ass":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Penis"],
        "Bottom parts": ["Asshole"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },
    "Pull Ass Off Of Cock":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Asshole"],
        "Bottom parts": ["Penis"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },


    "Finger Ass": 
    {
        "positions": [ "Missionary", "Lap ride", "Prone Bone", "Mating Press", "Sixty-Nine", "From Behind", "Doggy", "Bent Over", "Cowgirl", "Reverse Cowgirl", "Kneeling", "Kneeling Over", "Standing", "Standing From Behind", "Oral Service", "Spooning", "Double Decker", "Against Wall From Behind", "Perched Oral Service", "Underneath Oral Service", "Laid Across On Back", "Laid Across On Stomach", "Laid Across Oral Service", "Sitting"],
        "action type": ["penetrate"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Asshole"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 5,
        "Bottom arousal": 35,
        "Top arousal cap": 300,
        "remember as": ["anal fingerbang", "given"],
        "Top dialogue tags": ["fingering ass"],
        "Bottom dialogue tags": ["ass fingered"],
    },
    "Finger Ass(Continue)": 
    {
        "positions": [ "Missionary", "Prone Bone", "Mating Press", "Sixty-Nine", "From Behind", "Doggy", "Bent Over", "Cowgirl", "Reverse Cowgirl", "Kneeling", "Kneeling Over", "Standing", "Standing From Behind", "Lap ride", "Oral Service", "Spooning", "Double Decker", "Against Wall From Behind", "Perched Oral Service", "Underneath Oral Service", "Laid Across On Back", "Laid Across On Stomach", "Laid Across Oral Service"],
        "action type": ["continue"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Asshole"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 5,
        "Bottom arousal": 35,
        "Top arousal cap": 300,
        "remember as": ["anal fingerbang", "given"],
        "Top dialogue tags": ["fingering ass"],
        "Bottom dialogue tags": ["ass fingered"],
    },
    "Stop Fingering Ass":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Hand"],
        "Bottom parts": ["Asshole"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": true,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },
    "Pull Ass Off Of Finger":
    {
        "positions": [],
        "action type": ["end"],
        "Top parts": ["Asshole"],
        "Bottom parts": ["Hand"],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },



    "Aftercare Kiss":
    {
        "positions": [],
        "action type": ["aftercare"],
        "Top parts": [],
        "Bottom parts": [],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },
    "Cuddle":
    {
        "positions": [],
        "action type": ["aftercare"],
        "Top parts": [],
        "Bottom parts": [],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },
    "Caress":
    {
        "positions": [],
        "action type": ["aftercare"],
        "Top parts": [],
        "Bottom parts": [],
        "Top cum locations": [],
        "Bottom cum locations": [],
        "masturbation": false,
        "take virginity": [],
        "Top arousal": 0,
        "Bottom arousal": 0,
    },
};